site_name: NOMAD HZB PV Plugin Documentation
repo_url: https://github.com/nomad-hzb/nomad-hysprint
edit_uri: ""

nav:
  - Home: index.md
  - Step by Step User Guide:
    - Overview: step-by-step_user_guide/00-overview.md
    - Spreadsheet Workflow: step-by-step_user_guide/01-spreadsheet_workflow.md
    - Upload Data: step-by-step_user_guide/02-upload_data.md
    - Upload Measurement: step-by-step_user_guide/03-upload_measurements.md
    - Voila Analysis Tools: step-by-step_user_guide/04-voila_analysis_tools.md
    - How to Cite: step-by-step_user_guide/05-how_to_cite.md
    - Contact: step-by-step_user_guide/06-contact.md
  
plugins:
  - search
theme:
  name: material
  palette:
    primary: '#2A4CDF'
    accent: '#008A67'
  font:
    text: 'Titillium Web'
  logo: assets/nomad-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
  custom_dir: docs/theme
# repo_url: https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - mkdocs-click
  - pymdownx.extra
extra:
  generator: false
  homepage: https://nomad-lab.eu
use_directory_urls: false
extra_css:
  - stylesheets/extra.css
# extra_javascript:
#   - javascript.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
